### ISSUE TITLE
Feedbacks

### ISSUE THREAD

**Issue by LucBerge** [dofapi/dofapi#1]
Hello !
First thank you for this online API, it woud help me a lot.

I have few feedbacks regarding [the explorer](https://fr.dofus.dofapi.fr/explorer/#/) : 

- `sets/{id}` does not work.
- Why `sets/{id}/weapons/` take an S and not `set/{id}/equipments/` ?
- It seams that the [supported items list](https://github.com/dofapi/dofapi#supported-items) is not up to date.

Also, I would be happy to contribut to the projet, let me know how.

**Comment by raczak** [comment]
Hello @LucBerge, first thank you for your feedback, it's very important for us to improve the tool.
Regarding the `set` category, I fix it and it's working now (an error in the model).
For the "s" of `sets/{id}/weapons/` it's an oversight in route definition lol ^^' 

If you want to help, you are more than welcome on our [discord channel](https://discord.dofapi.fr/)
